version: "3.8"

services:
   web:
     build:
        context: .
        dockerfile: Dockerfile
     command: sh -c "./entrypoint.sh"
     volumes:
           - .:/app

     depends_on:
        - db
        - redis
     networks:
      - backend

   db:
     image: postgres
     environment:
             POSTGRES_DB: postgres
             POSTGRES_USER: postgres
             POSTGRES_PASSWORD: faak@0496
     ports:
        - "5432:5432"
     networks:
       - backend

   redis:
        image: redis
        ports:
           - "6379:6379"
        networks:
          - backend
 
   pgadmin:
         image: dpage/pgadmin4
         environment:
                 PGADMIN_DEFAULT_EMAIL: admin@example.com
                 PGADMIN_DEFAULT_PASSWORD: admin
         ports:
              - "5050:80"
         networks:
          - backend

   nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - backend

networks:
  backend:
    driver: bridge

